import { MarkdownUtils } from "../utils/MarkdownUtils";

export class WorkflowSectionGenerator implements ISectionGenerator {
	constructor(private readonly workflowRun: WorkflowRun | null) {}

	generate(): string {
		if (!this.workflowRun) return "";

		let content = "";
		content += MarkdownUtils.newLine();
		content += `## For Nerds${MarkdownUtils.newLine()}${MarkdownUtils.newLine()}`;

		content += `This file was automatically generated by [GitHub Actions](${this.workflowRun.html_url}) using [Bun](https://bun.sh) & [TypeScript](https://www.typescriptlang.org/).${MarkdownUtils.newLine()}${MarkdownUtils.newLine()}`;

		const startTime = this.workflowRun.run_started_at
			? new Date(this.workflowRun.run_started_at).toUTCString()
			: "Unknown";
		content += `- **Workflow Name:** ${this.workflowRun.name}${MarkdownUtils.newLine()}`;
		content += `- **Run Number:** ${this.workflowRun.run_number}${MarkdownUtils.newLine()}`;
		content += `- **Run ID:** [${this.workflowRun.id}](${this.workflowRun.html_url})${MarkdownUtils.newLine()}`;
		content += `- **Trigger Event:** ${this.workflowRun.event}${MarkdownUtils.newLine()}`;
		content += `- **Run Started:** ${startTime} (GMT)${MarkdownUtils.newLine()}`;
		return content;
	}
}
