import { MarkdownUtils } from "../utils/MarkdownUtils";

export class WorkflowSectionGenerator implements ISectionGenerator {
	constructor(private readonly workflowRun: WorkflowRun | null) {}

	generate(): string {
		if (!this.workflowRun) return "";

		let content = "";
		content += MarkdownUtils.newLine();
		content += `## For Nerds${MarkdownUtils.newLine()}${MarkdownUtils.newLine()}`;

		content += `This file was automatically generated by [GitHub Actions](${this.workflowRun.html_url}) using [Bun](https://bun.sh) & [TypeScript](https://www.typescriptlang.org/).${MarkdownUtils.newLine()}${MarkdownUtils.newLine()}`;

		const startTime = this.workflowRun.run_started_at
			? new Date(this.workflowRun.run_started_at).toLocaleString("en-US", {
					timeZone: "UTC",
				})
			: "Unknown";

		content += `- **Workflow Name:** ${this.workflowRun.name}${MarkdownUtils.newLine()}`;
		content += `- **Run Number:** ${this.workflowRun.run_number}${MarkdownUtils.newLine()}`;
		content += `- **Latest Run Status:** ${this.workflowRun.status} (${this.workflowRun.conclusion})${MarkdownUtils.newLine()}`;
		content += `- **Run ID:** [${this.workflowRun.id}](${this.workflowRun.html_url})${MarkdownUtils.newLine()}`;
		content += `- **Trigger Event:** ${this.workflowRun.event}${MarkdownUtils.newLine()}`;
		content += `- **Run Started:** ${startTime} (UTC)${MarkdownUtils.newLine()}`;

		if (this.workflowRun.head_commit) {
			content += `- **Commit:** [\`${this.workflowRun.head_sha.substring(0, 7)}\`](https://github.com/${this.workflowRun.repository.full_name}/commit/${this.workflowRun.head_sha}) - ${this.workflowRun.head_commit.message?.split("\n")[0]}${MarkdownUtils.newLine()}`;
		}

		return content;
	}
}
